# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_remove_atividade_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Evento')),
                ('issn', models.CharField(max_length=200, verbose_name='issn')),
            ],
            bases=('evento.evento',),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEHora', models.DateField(verbose_name='dataEHora')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeInscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='descricao')),
            ],
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='tipo_atividade',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='abertura_evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='abertura_inscricoes',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='apresentacao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='encerramento_evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='encerramento_inscricoes',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='limite_inscricoes',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='local',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='programacao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='publico_alvo',
        ),
        migrations.AddField(
            model_name='evento',
            name='cep',
            field=models.CharField(max_length=200, null=True, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.CharField(max_length=200, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='evento',
            name='dataEHoraDeInicio',
            field=models.DateField(null=True, verbose_name='dataEHoraDeInicio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(max_length=200, null=True, verbose_name='endereco'),
        ),
        migrations.AddField(
            model_name='evento',
            name='eventoPrincipal',
            field=models.CharField(max_length=200, null=True, verbose_name='eventoPrincipal'),
        ),
        migrations.AddField(
            model_name='evento',
            name='logotipo',
            field=models.CharField(max_length=200, null=True, verbose_name='logotipo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='palavrasChave',
            field=models.CharField(max_length=200, null=True, verbose_name='palavrasChave'),
        ),
        migrations.AddField(
            model_name='evento',
            name='sigla',
            field=models.CharField(max_length=200, null=True, verbose_name='sigla'),
        ),
        migrations.AddField(
            model_name='evento',
            name='uf',
            field=models.CharField(max_length=200, null=True, verbose_name='uf'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=200, null=True, verbose_name='nome'),
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Pessoa')),
                ('curriculo', models.CharField(max_length=200, verbose_name='curriculo')),
            ],
            bases=('evento.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Pessoa')),
                ('cpf', models.CharField(max_length=200, verbose_name='cpf')),
            ],
            bases=('evento.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Pessoa')),
                ('cnpj', models.CharField(max_length=200, verbose_name='cnpj')),
                ('razaoSocial', models.CharField(max_length=200, verbose_name='razaoSocial')),
            ],
            bases=('evento.pessoa',),
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='TipoAtividade',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='tipoDeInscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.TipoDeInscricao'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.EventoCientifico'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inscricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Inscricao'),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='autor',
            name='artigos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.ArtigoCientifico'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='autores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Autor'),
        ),
    ]
